"""
config.py — Central configuration for the skin cancer detection project.

All paths, class definitions, preprocessing constants, and training
hyperparameters live here so that every module imports from one source of truth.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

# Repository root — two levels up from this file (src/config.py → repo root)
PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent

IMAGE_DIR: Path = PROJECT_ROOT / "data" / "raw" / "images"
PROCESSED_DIR: Path = PROJECT_ROOT / "data" / "processed"
MODELS_DIR: Path = PROJECT_ROOT / "models"
SCRIPTS_DIR: Path = PROJECT_ROOT / "scripts"

# Ensure models directory exists so saving artifacts never fails
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Class definitions — single source of truth across all modules
# ---------------------------------------------------------------------------

CLASS_NAMES: list[str] = [
    "akiec",  # Actinic keratoses / intraepithelial carcinoma
    "bcc",    # Basal cell carcinoma
    "bkl",    # Benign keratinocytic lesions
    "df",     # Dermatofibroma
    "mel",    # Melanoma
    "nv",     # Melanocytic nevi
    "vasc",   # Vascular lesions
]

NUM_CLASSES: int = len(CLASS_NAMES)

CLASS_TO_INDEX: dict[str, int] = {name: idx for idx, name in enumerate(CLASS_NAMES)}
INDEX_TO_CLASS: dict[int, str] = {idx: name for name, idx in CLASS_TO_INDEX.items()}

# Human-readable descriptions for API responses
CLASS_FULL_NAMES: dict[str, str] = {
    "akiec": "Actinic keratoses and intraepithelial carcinoma",
    "bcc":   "Basal cell carcinoma",
    "bkl":   "Benign keratinocytic lesions",
    "df":    "Dermatofibroma",
    "mel":   "Melanoma",
    "nv":    "Melanocytic nevi",
    "vasc":  "Vascular lesions",
}

# ---------------------------------------------------------------------------
# Preprocessing constants — must match exactly between training and inference
# ---------------------------------------------------------------------------

IMAGE_SIZE: int = 224  # pixels (square)

IMAGENET_MEAN: list[float] = [0.485, 0.456, 0.406]
IMAGENET_STD: list[float]  = [0.229, 0.224, 0.225]

# ---------------------------------------------------------------------------
# DataLoader settings
# ---------------------------------------------------------------------------

BATCH_SIZE: int = 32
# On Windows, num_workers > 0 in DataLoader requires if __name__ == "__main__"
# guards in scripts. Keep at 0 for safety across platforms.
NUM_WORKERS: int = 0

# ---------------------------------------------------------------------------
# Reproducibility
# ---------------------------------------------------------------------------

RANDOM_SEED: int = 42

# ---------------------------------------------------------------------------
# Training hyperparameters — SimpleCNN baseline
# ---------------------------------------------------------------------------

SIMPLE_CNN_CONFIG: dict = {
    "model_type": "simple_cnn",
    "num_epochs": 15,
    "learning_rate": 1e-3,
    "weight_decay": 1e-4,
    "batch_size": BATCH_SIZE,
    "early_stopping_patience": 5,
    "checkpoint_name": "skin_lesion_cnn_baseline.pth",
}

# ---------------------------------------------------------------------------
# Training hyperparameters — ResNet18 transfer learning
# ---------------------------------------------------------------------------

RESNET18_CONFIG: dict = {
    "model_type": "resnet18",
    "num_epochs": 15,
    # Lower LR for fine-tuning — pre-trained weights are already good
    "learning_rate": 3e-4,
    "weight_decay": 1e-4,
    "batch_size": BATCH_SIZE,
    "early_stopping_patience": 5,
    # Freeze all layers except layer4 + fc — train only ~2.8M / 11M params
    "freeze_backbone": True,
    "checkpoint_name": "skin_lesion_resnet18_baseline.pth",
}

# ---------------------------------------------------------------------------
# Inference / API defaults
# ---------------------------------------------------------------------------

# Default model used by the API if MODEL_TYPE env var is not set
DEFAULT_MODEL_TYPE: str = "resnet18"
DEFAULT_MODEL_CHECKPOINT: str = "skin_lesion_resnet18.pth"

# Maximum allowed upload size for the /predict endpoint (bytes)
MAX_UPLOAD_SIZE_BYTES: int = 10 * 1024 * 1024  # 10 MB

ALLOWED_IMAGE_CONTENT_TYPES: set[str] = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/bmp",
}

MEDICAL_DISCLAIMER: str = (
    "This result is generated by a research AI model for educational purposes only. "
    "It is NOT a medical diagnosis and should NOT be used as a substitute for "
    "professional medical advice. Please consult a qualified dermatologist for any "
    "skin concerns."
)
